### ISSUE TITLE
approximate Pi

### ISSUE THREAD

**Issue by billautomata** [nodechomsky/primes#5]
write a program that uses `Math.random()` to pick two points both within a range `[ -x, x ]`

then determine if the point lies within a circle with a radius of `x`

if yes, count it as a `hit`

the ratio of `hit` to `total_runs` should be `Math.PI`

have the program run until it approximates Pi to a specific `delta` value

``` javascript
var delta = 0.001
if( Math.abs(approximation-Math.PI) < delta ) { done() }
```
# tip

the distance function looks like

`d = sqrt( (x2-x1)^2 + (y2-y1)^2 )`

but since the origin point is always `(0,0)` when testing if it is in the circle you can shorten it to 

`d = sqrt( x^2 + y^2 )`

use `Math.sqrt` and `Math.pow`

**Comment by nodechomsky** [comment]
Pi.js produces an approximation with a delta of n. It usually makes several attempts before it actually arrives at a value, other times it converges to approximately the value 3.6... This is hypothesized to be an eccentricity of the Math.random() function. Each attempt is terminated when it does not converge to the specified delta after it has used Math.floor( 0.1 / delta ) number of data points.
